name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: harnithlokesh
          outputs: |
            dist/github-snake.svg?color_snake=%2339FF14&color_dots=%23161B22,%230E4429,%23006D32,%2326A641,%2339FF14
            dist/github-snake-dark.svg?color_snake=%2339FF14&color_dots=%23161B22,%230E4429,%23006D32,%2326A641,%2339FF14

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
